export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';

export const USER_LIST_FETCH_SUCCESS = 'USER_LIST_FETCH_SUCCESS';
export const USER_LIST_FETCH_FAILED = 'USER_LIST_FETCH_FAILED';
export const USER_LIST_FETCH_REQUESTED = 'USER_LIST_FETCH_REQUESTED';
